version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8081:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8083:8083" # Roadrunner PHP application server (optional)
    depends_on:
      - db
      #   - redis
      #   - mailhog
      # - webdriver
    volumes:
      - ./src:/var/www/html
      # - node-data:/var/www/html/frontend/node_modules
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf

  db:
    # image: mysql:5.7
    # image: mariadb:5.5-trusty
    image: mariadb/server:10.3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/cyfons.cnf
      - ./logs:/var/log/mysql2
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8033:80
    volumes:
      - "phpmyadminSession:/sessions"

    # redis:
    #   image: redis:3-alpine

  #   mailhog:
  #     image: mailhog/mailhog
  #     ports:
  #       - "8082:8025"

  maildev:
    image: kanemu/maildev-with-iconv
    ports:
      - 8025:80

  # webdriver:
  #   image: selenium/standalone-chrome
  #   volumes:
  #     - /dev/shm:/dev/shm

volumes:
  # node-data:
  #   driver: local
  mysql-data:
    driver: local
  phpmyadminSession:
    driver: local

networks:
  default:
    driver: bridge
